FROM python:3.8
ENV PYTHONUNBUFFERED 1

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -yq \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    ffmpeg

COPY ./requirements.txt /requirements.txt
RUN python3 -m pip install -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -r requirements.txt

COPY ./backend /app
WORKDIR /app

ENTRYPOINT [ "gunicorn", "-b", "0.0.0.0:5000", "-w", "4", "api:app" ]