FROM python:3.8
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -yq \
    ffmpeg

COPY ./requirements.txt /requirements.txt
RUN python3 -m pip install -r requirements.txt

COPY ./backend /app
WORKDIR /app

ENTRYPOINT [ "gunicorn", "-b", "0.0.0.0:5000", "-w", "4", "api:app" ]