name: Deploy

on:
  push:
    branches: [master]

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to AliYun Container Registry
      uses: docker/login-action@v1 
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_CR_USERNAME }}
        password: ${{ secrets.ALIYUN_CR_TOKEN }}
    - name: Setup psake
      run: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; Install-Module -Name psake
    - name: Download models
      run: Invoke-psake download-models
    - name: Build frontend
      run: Invoke-psake build-frontend
    - name: Push frontend images
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          stardustdl/movie2comic:frontend
          registry.cn-hangzhou.aliyuncs.com/stardustdl/movie2comic:frontend
    - name: Push backend images
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          stardustdl/movie2comic:backend
          registry.cn-hangzhou.aliyuncs.com/stardustdl/movie2comic:backend
    
